### ISSUE TITLE
Rename to screwdriver?

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/api#27]
I noticed that both kubernetes and spinnaker have their main repository be named after the git organization/product.  Should we do the same?

If so, the API would be the primary component of SD and as such we should rename it.

**Comment by catto** [comment]
I think renaming is better because `api` is a very common word and confusing. It can lead to a name collision when someone forks this repository (api, api-1, api-2, ...). I noticed it when forking this repository.

Is `screwdriver-cd` the official product name? If not, I think `screwdriver-cd/screwdriver-cd` is a bit verbose. How about `screwdriver-cd/screwdriver`?

Another option I can conceive is add `screwdriver-` prefix to all the public repositories. `screwdriver-cd` repository is for guide or info, like travis-ci.
https://github.com/travis-ci/travis-ci
https://github.com/travis-ci/travis-api

**Comment by stjohnjohnson** [comment]
It's tough, because `screwdriver` was taken in various places (github user, docker org), but we were able to get `screwdriver-cd` across the board.  So the product is going to be called `screwdriver` and the domain is `screwdriver.cd`.

I'd like this to become the _main_ repository for all of screwdriver, that way we can use it to track most issues and milestones.

The Travis example is interesting.  Here are the links to [k8s](https://github.com/kubernetes/kubernetes) and [spinnaker](https://github.com/spinnaker/spinnaker).

**Comment by d2lam** [comment]
How about screwdriver-api?

**Comment by jer** [comment]
I like `screwdriver-cd/screwdriver`. It highlights the fact that Screwdriver really is, at its core, an API that you can hang plugins off of. It is the product name, you would check it out to a `screwdriver` directory.

**Comment by tkyi** [comment]
Unless we decide to change the name of our product to `screwdriver-cd`, using `screwdriver-cd/screwdriver` makes the most sense to me if we are using this as the main repository.
